# run with "docker compose up -d"
version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=items
    ports:
      - "5433:5432"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.10
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --overprovisioned
    ports:
      - 9092:9092
