name: Dependencies integration check

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  integration-check:
    runs-on: ubuntu-latest

    steps:
      - name: Extract repository name
        shell: bash
        run: echo "repository=${{ github.event.pull_request.head.repo.full_name || github.repository }}" >> $GITHUB_OUTPUT
        id: extract_repository
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: yes '' | sbt new ${{ steps.extract_repository.outputs.repository }} --branch ${{ steps.extract_branch.outputs.branch }}
      - run: cd zio-scala-3-project && sbt compile && sbt test
